#
#  __  __            _         _         _                  _
# |  \/  | __ _ _ __| | ____ _| |_ __ _ | |_ ___  _ __ ___ | |
# | |\/| |/ _` | '__| |/ / _` | __/ _` || __/ _ \| '_ ` _ \| |
# | |  | | (_| | |  |   < (_| | || (_| || || (_) | | | | | | |
# |_|  |_|\__,_|_|  |_|\_\__,_|\__\__,_(_)__\___/|_| |_| |_|_|
#
#                                           waylonwalker.com

[markata]
# bump site version to bust GitHub actions cache
site_version = 13

## Markata Setup
glob_patterns = "pages/**/*.md"
## glob_patterns = "pages/**/*spaceflights*.md"
output_dir = "markout"
assets_dir = "static"
hooks = [
   "markata.plugins.publish_source",
   "plugins.index",
   "plugins.slug",
   "plugins.one_line_link",
   "default",
   'plugins.related',
   'plugins.seo_amp',
   'plugins.publish_amp',
   'plugins.custom_seo',
   'plugins.gif_to_mp4',
   'plugins.youtube',
   'plugins.rss_tag',
   ]
disabled_hooks = ["markata.plugins.covers", 'markata.plugins.flat_slug']

## Site Config
url = "https://waylonwalker.com"
images_url = "https://images.waylonwalker.com"
title = "Waylon Walkers Digital Garden"
description = "I write about how I use python and linux in data science."
rss_description = "Waylon Walkers posts"
author_name = "Waylon Walker"
author_email = "waylon@waylonwalaker.com"
icon = "8bitcc.png"
lang = "en"
post_template = "pages/templates/post_template.html"
amp_template = "pages/templates/post_template.amp.html"
theme_color = "#322D39"
background_color = "#B73CF6"
start_url = "/"
site_name = "Waylon Walker"
short_name = "ww"
display = "minimal-ui"
twitter_card = "summary_large_image"
twitter_creator = "@_waylonwalker"
twitter_site = "@_waylonwalker"

[markata.archive]
archive_template="pages/templates/archive_template.html"

[markata.archive.pages.archive]
filters=[
    "date<=today",
    "templateKey=='blog-post'",
    "status.lower()=='published'",
]

[markata.archive.pages.draft]
filters=[
    "status=='draft'",
]

[markata.archive.pages.scheduled]
filters=[
    "date>today",
]

[markata.archive.pages.today]
filters=[
    "date==today",
]

[markata.archive.pages.python]
filters=[
    "date<=today",
    "'python' in tags",
]

[markata.archive.pages.python-draft]
filters=[
    "date<=today",
    "'python' in tags",
    "status=='draft'",
]

[markata.archive.pages.linux]
filters=[
    "date<=today",
    "'linux' in tags",
]

[markata.archive.pages.linux-draft]
filters=[
    "date<=today",
    "'linux' in tags",
    "status=='draft'",
]

[markata.archive.pages.vim]
filters=[
    "date<=today",
    "'vim' in tags",
]

[markata.archive.pages.vim-draft]
filters=[
    "date<=today",
    "'vim' in tags",
    "status=='draft'",
]

[markata.archive.pages.kedro]
filters=[
    "date<=today",
    "'kedro' in tags",
]

[markata.archive.pages.kedro-draft]
filters=[
    "date<=today",
    "'kedro' in tags",
    "status=='draft'",
]

[markata.archive.pages.gratitude]
template="pages/templates/archive_template.html"
card_template="pages/templates/gratitude_card.html"
filters=[
    "date<=today",
    "templateKey == 'gratitude'",
]

[markata.archive.pages.til]
template="pages/templates/archive_template.html"
card_template="pages/templates/gratitude_card.html"
filters=[
    "date<=today",
    "templateKey == 'til'",
]

[markata.archive.pages.til-vim]
template="pages/templates/archive_template.html"
card_template="pages/templates/gratitude_card.html"
filters=[
    "date<=today",
    "templateKey == 'til'",
    "'vim' in tags",
]

[[markata.covers]]
name='-dev'
template = "static/cover-template.png"
font = "./.github/scripts/waterlilly-script.ttf"
font_color = "rgb(255,255,255)"

[[markata.covers]]
name='-og'
template = "static/og-template.png"
font = "./.github/scripts/waterlilly-script.ttf"
font_color = "rgb(255,255,255)"
# text_key = 'long_description'
text_font = "./static/JosefinSans-Regular.ttf"
text_font_color = "rgb(200,200,200)"

[[markata.covers]]
name='-hashnode'
template = "static/hashnode-template.png"
font = "./.github/scripts/waterlilly-script.ttf"
font_color = "rgb(255,255,255)"

[[markata.seo]]
name = "og:type"
property = "og:type"
content = "article"

[[markata.seo]]
name = "og:author"
property = "og:author"
content = "Waylon Walker"

[[markata.seo]]
name = "og:site_name"
property = "og:site_name"
content = "Waylon Walker"

[[markata.seo]]
name = "theme-color"
content="#322D39"
